packages:
  - packages/*

autoInstallPeers: false

peerDependencyRules:
  ignoreMissing:
    - '@emnapi/core'
    - '@emnapi/runtime'
    - markdown-it
    - search-insights

onlyBuiltDependencies:
  - esbuild
